---
- hosts: main
  user: vagrant
  sudo: true
  roles:
    # - common
    # - docker
    # - nginx
    - git-deploy
    # - { role: Sirupsen.ansible-ruby-common, 
    #     ruby_library_version:   "2.1.0",
    #     ruby_version:           "ruby-2.1.0",
    #     ruby_checksum:          "3538ec1f6af96ed9deb04e0965274528162726cc9ba3625dcf23648df872d09d",
    #     ruby_download_location: "http://cache.ruby-lang.org/pub/ruby/2.1/{{ ruby_version }}.tar.gz",
    #     ruby_bundler_flags: "--no-document" }
